FROM postgres:15-alpine

COPY ./docker/postgres/init.sql /docker-entrypoint-initdb.d/
COPY ./docker/postgres/init-data.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/*.sh


HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD pg_isready -U ${POSTGRES_USER} || exit 1

EXPOSE 5432

LABEL maintainer="your-email@example.com"
LABEL version="1.0"
LABEL description="PostgreSQL for NestJS REST API"