services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - app-net

  app:
    build: .
    container_name: nest_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app      
      # - /app/node_modules
    command: npm run start:dev
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs:
